name: GEMS3K

dependencies:
  - ccache  # [unix]
  - clangxx_osx-64  # [osx]
  - cmake>=3.13
  - git
  - gxx_linux-64  # [linux]
  - ninja
  - nlohmann_json
  - thermofun =0.4.0
  - vs2019_win-64  # [win]
