name: GEMS3K

dependencies:
  - gxx_linux-64=9.3.0  # [linux]
  - cmake>=3.7
  - ninja # [unix]
  - make  # [win]
  - git
  - ccache  # [unix]
  - nlohmann_json

environment:

  LD_LIBRARY_PATH:                                                   # [unix]
    - {{ root }}/artifacts/lib                                       # [unix]

  PATH:                                                              # [win]
    - {{ root }}\artifacts\bin                                       # [win]
