name: GEMS3K

channels:
  - conda-forge

dependencies:
  - gxx_linux-64  # [linux]
  - cmake>=3.13
  - ninja
  - git
  - ccache  # [unix]
  - nlohmann_json
  - thermofun>=0.4.3

environment:

  LD_LIBRARY_PATH:                                                   # [unix]
    - {{ root }}/artifacts/lib                                       # [unix]

  PATH:                                                              # [win]
    - {{ root }}\artifacts\bin                                       # [win]
